#NLP Fundamentals

# Text Cleaning

Text cleaning is the process of **removing noise from raw text** so that machines can process it effectively.

## Why is Text Cleaning Important?

Raw text often contains:

- Uppercase and lowercase variations
- Punctuation and symbols
- Numbers and emojis
- Extra white spaces

These add **noise**, not meaning.

## Common Text Cleaning Operations

- Convert text to lowercase
- Remove punctuation
- Remove numbers
- Remove special characters
- Normalize white spaces

## Benefits of Text Cleaning

- Smaller vocabulary
- Better model performance
- Faster processing

In [ ]:
#1. Text lowercasing

text1 = "Hello World"
print(text1.lower())

text2 = "NLP is FuN"
print(text2.lower())

hello world
nlp is fun


In [ ]:
#2. Removing Punctuations

import string

text1 = "Hello! How are you?"
print(text1.translate(str.maketrans("", "", string.punctuation)))

text2 = "I'm enjoying NLP."
print(text2.translate(str.maketrans("", "", string.punctuation)))

Hello How are you
Im enjoying NLP


In [ ]:
#3. Remove Numbers

import re  #regex library

text1 = "NLP 101 is easy"
print(re.sub(r'\d+', '', text1)) #remove digits

text2 = "I have 3 dogs and 2 cats"
print(re.sub(r'\d+', '', text2))

text = "Hello, World! How's it going? #NLP 😊" #capture punctuation
punct = re.findall(r"[^\w\s]", text)
print(punct)

NLP  is easy
I have  dogs and  cats
[',', '!', "'", '?', '#', '😊']


##4. Tokenization

Tokenization is the process of **breaking text into smaller units** called **tokens**.

### Types of Tokenization

1. **Word Tokenization** 📝  
   Splits text into individual words.

2. **Sentence Tokenization** 📄  
   Splits text into individual sentences.

### Why is Tokenization Important?

- Models do not understand raw text.
- Tokens are the basic units used in NLP.
- Most NLP operations work on tokens, not full text.

### Example

**Input:**

```text
I love NLP
```

**Output:**

```python
["I", "love", "NLP"]
```

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download("punkt_tab")  # download tokenizer model

text1 = "NLP is amazing"
print(word_tokenize(text1))

text2 = "I have a cat and a dog"
print(word_tokenize(text2))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['NLP', 'is', 'amazing']
['I', 'have', 'a', 'cat', 'and', 'a', 'dog']


## 5. Stopword Removal

Stopwords are **very common words** that usually do not add much meaning to a sentence.

### Examples of Stopwords

- is
- the
- and
- of
- to
- in

### Why Remove Stopwords?

- They appear in almost every document.
- They increase the feature vector size.
- They dilute important information.

### Benefits of Stopword Removal

- Text becomes more meaningful.
- Feature space is reduced.
- Improves the efficiency of many NLP models.

In [ ]:
from nltk.corpus import stopwords

nltk.download("stopwords")

# Load English stopwords
stop_words = set(stopwords.words("english"))

tokens1 = word_tokenize("NLP is a subfield of AI")
print(tokens1)
print([w for w in tokens1 if w.lower() not in stop_words])

tokens2 = word_tokenize("I am a student")
print(tokens2)
print([w for w in tokens2 if w.lower() not in stop_words])

['NLP', 'is', 'a', 'subfield', 'of', 'AI']
['NLP', 'subfield', 'AI']
['I', 'am', 'a', 'student']
['student']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# Stemming

Stemming reduces words to their **root form** using **rule-based methods**.

## Examples

- `running` → `run`
- `studies` → `studi`
- `playing` → `play`

## Characteristics of Stemming

- Fast
- Rule-based
- Output may not be a real dictionary word

## Use Cases

- Search engines
- Information retrieval
- Text classification
- Spam detection

In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

words1 = ["running", "runs", "ran"]
print([stemmer.stem(word) for word in words1])

words2 = ["study", "studies", "studying"]
print([stemmer.stem(word) for word in words2])

['run', 'run', 'ran']
['studi', 'studi', 'studi']


# Lemmatization

Lemmatization reduces words to their **dictionary base form (lemma)**.

## Examples

- `running` → `run`
- `studies` → `study`
- `better` → `good`

## Characteristics of Lemmatization

- Uses vocabulary and grammar
- More accurate than stemming
- Slower than stemming

## Preferred In

- Chatbots
- NLP pipelines
- Semantic analysis
- Machine translation


In [ ]:
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')  #dictionary for lemmatization
lemmatizer = WordNetLemmatizer() #initialize

words1 = ["running", "runs", "ran"]
print([lemmatizer.lemmatize(word) for word in words1])

[nltk_data] Downloading package wordnet to /root/nltk_data...


['running', 'run', 'ran']


# One-Hot Encoding

One-Hot Encoding represents each word as a **binary vector**.

## How It Works

- Vocabulary size = Vector length
- Each word gets a unique index
- Presence → `1`
- Absence → `0`

## Example Vocabulary

```python
["ai", "love", "nlp"]
```

**Encoding:**

```python
"nlp"  → [0, 0, 1]
"love" → [0, 1, 0]
"ai"   → [1, 0, 0]
```

## Limitations

- Creates high-dimensional vectors for large vocabularies.
- Does not capture semantic meaning between words.
- Sparse representation (mostly zeros).
- Ignores the order of words.

In [ ]:
import numpy as np

vocab = ["ai", "data", "learning", "nlp"]

def one_hot(word, vocab):
    vector = np.zeros(len(vocab))
    print (vector)

    if word in vocab:
      vector[vocab.index(word)] = 1
    return vector


for word in vocab:
  print(word,"->", one_hot(word, vocab))

[0. 0. 0. 0.]
ai -> [1. 0. 0. 0.]
[0. 0. 0. 0.]
data -> [0. 1. 0. 0.]
[0. 0. 0. 0.]
learning -> [0. 0. 1. 0.]
[0. 0. 0. 0.]
nlp -> [0. 0. 0. 1.]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = ["I love NLP", "AI is fun"]

vectorizer = CountVectorizer(binary=True)   # Create a CountVectorizer object

X = vectorizer.fit_transform(sentences)

print(vectorizer.get_feature_names_out())
print(X)
print(X.toarray())    #One-hot vectors

['ai' 'fun' 'is' 'love' 'nlp']
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (2, 5)>
  Coords	Values
  (0, 3)	1
  (0, 4)	1
  (1, 0)	1
  (1, 2)	1
  (1, 1)	1
[[0 0 0 1 1]
 [1 1 1 0 0]]


# ⚠️ Important: Core Difference Between the Two Outputs

Although both outputs look like **one-hot encoding**, they represent **different things**.

## 1. Word-Level One-Hot Encoding

- Each **individual word** is represented by its own vector.
- The vector has **exactly one `1`** and the remaining values are `0`.
- Used to uniquely identify a word.

**Example:**

```python
Vocabulary = ["ai", "love", "machine", "nlp"]

"nlp" → [0, 0, 0, 1]
```

---

## 2. Document-Level Binary Encoding (CountVectorizer)

- Each **document (sentence)** is represented by a vector.
- The vector indicates the **presence (`1`) or absence (`0`)** of words in the vocabulary.
- A document can contain **multiple `1`s** because it may contain multiple words.
- This is actually a **Binary Bag of Words**, not true one-hot encoding.

### Example

**Vocabulary:**

```python
["ai", "love", "machine", "nlp"]
```

**Sentence:**

```text
I love NLP
```

**Binary Bag of Words:**

```python
[0, 1, 0, 1]
```

---

## In Short

| Word-Level One-Hot Encoding | Document-Level Binary Encoding |
|-----------------------------|--------------------------------|
| Encodes **individual words** | Encodes **entire documents/sentences** |
| Exactly **one `1`** in every vector | Can contain **multiple `1`s** |
| Identifies a single word | Indicates which words appear in a document |
| Used for word representation | Used for document representation (e.g., `CountVectorizer(binary=True)`) |

# Bag of Words

Bag of Words represents text by **counting the frequency of words** in a document.

## Key Ideas

- Ignores grammar and word order.
- Considers how many times each word appears.
- Creates a **document-word matrix**.
- Each row represents a document, and each column represents a word in the vocabulary.

## Example

**Sentence:**

```text
I love love NLP
```

**Vocabulary:**

```python
["I", "love", "NLP"]
```

**Bag of Words Vector:**

```python
[1, 2, 1]
```

Here, `"love"` appears **2** times.

---

## Advantages

- Simple and easy to understand.
- Easy to implement.
- Works well as a baseline for text classification tasks.

## Limitations

- Ignores word order and grammar.
- Does not capture the meaning or context of words.
- Common words can dominate the representation.
- Produces high-dimensional and sparse vectors for large vocabularies.

In [ ]:
vectorizer = CountVectorizer()  #Counts word frequency

sentences = ["I love NLP. I also love pizza.","I am typing and I love AI"]
X = vectorizer.fit_transform(sentences)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['ai' 'also' 'am' 'and' 'love' 'nlp' 'pizza' 'typing']
[[0 1 0 0 2 1 1 0]
 [1 0 1 1 1 0 0 1]]


In [ ]:
# Import the required class
from sklearn.feature_extraction.text import CountVectorizer

# Input documents
documents = [
    "I love love NLP",
    "I love AI",
    "NLP and AI are powerful"
]

# Initialize CountVectorizer with stopword removal
vectorizer = CountVectorizer(stop_words='english')

# Fit the vectorizer and transform documents into BoW matrix
bow_matrix = vectorizer.fit_transform(documents)

# Display the learned vocabulary
print("Vocabulary (column order):")
print(vectorizer.get_feature_names_out())

# Display the Bag of Words matrix
print("\nBag of Words Matrix:")
print(bow_matrix.toarray())

Vocabulary (column order):
['ai' 'love' 'nlp' 'powerful']

Bag of Words Matrix:
[[0 2 1 0]
 [1 1 0 0]
 [1 0 1 1]]


# TF-IDF (Term Frequency – Inverse Document Frequency)

TF-IDF measures **how important a word is to a document** relative to a collection of documents.

## Intuition

- Words that appear frequently in one document but are rare across all documents are considered important.
- Common words receive lower weights.

## Components

- **TF (Term Frequency):** How often a word appears in a document.
- **IDF (Inverse Document Frequency):** How rare the word is across all documents.

## Why TF-IDF is Better than Bag of Words (BoW)

- Reduces the impact of very common words.
- Highlights more meaningful and informative terms.
- Produces better features for many NLP tasks like text classification and information retrieval.

In [ ]:
# Import TF-IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Input documents (same as previous examples)
documents = [
    "I love love NLP",
    "I love AI",
    "NLP and AI are powerful"
]

# Initialize TF-IDF vectorizer with stopword removal
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

# Fit the model and transform documents into TF-IDF matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

# Display the learned vocabulary (column order)
print("Vocabulary (column order):")
print(tfidf_vectorizer.get_feature_names_out())

# Display the TF-IDF matrix
print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())

Vocabulary (column order):
['ai' 'love' 'nlp' 'powerful']

TF-IDF Matrix:
[[0.         0.89442719 0.4472136  0.        ]
 [0.70710678 0.70710678 0.         0.        ]
 [0.51785612 0.         0.51785612 0.68091856]]


# Part-of-Speech (POS) Tagging

POS Tagging assigns **grammatical roles** to words in a sentence.

## Common POS Tags

- Noun
- Verb
- Adjective
- Adverb
- Pronoun
- Preposition

## Example

**Sentence:**

```text
I love NLP
```

**POS Tags:**

- **I** → Pronoun
- **love** → Verb
- **NLP** → Proper Noun

## Applications

- Grammar checking
- Keyword extraction
- Syntax analysis
- Named Entity Recognition (NER)
- Machine Translation

In [ ]:
import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# Download the POS tagger model
nltk.download('averaged_perceptron_tagger_eng')

# Tokenize the sentence
tokens = word_tokenize("I love NLP")

# Perform POS tagging
print(pos_tag(tokens))

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


[('I', 'PRP'), ('love', 'VBP'), ('NLP', 'RB')]


# Named Entity Recognition (NER)

Named Entity Recognition (NER) identifies **real-world entities** in text.

## Common Entity Types

- Person
- Organization
- Location
- Date
- Time
- Money

## Example

**Sentence:**

```text
Elon Musk founded SpaceX.
```

**Recognized Entities:**

- **Elon Musk** → PERSON
- **SpaceX** → ORGANIZATION

## Applications

- Resume parsing
- News analysis
- Information extraction
- Search engines
- Chatbots and virtual assistants

In [ ]:
!pip install -q spacy
!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 31.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
import spacy

# Load the English language model
nlp = spacy.load("en_core_web_sm")

# Input text
doc1 = nlp("Elon Musk founded SpaceX in 2002")

# Print named entities and their labels
for ent in doc1.ents:
    print(ent.text, ent.label_)

Elon Musk PERSON
2002 DATE
